if(TARGET HDF5::C AND NOT TARGET hdf5::hdf5)
    add_library(hdf5::hdf5 INTERFACE IMPORTED)
    set_property(TARGET hdf5::hdf5 PROPERTY INTERFACE_LINK_LIBRARIES HDF5::C)
endif()
if(TARGET HDF5::HL AND NOT TARGET hdf5::hdf5_hl)
    add_library(hdf5::hdf5_hl INTERFACE IMPORTED)
    set_property(TARGET hdf5::hdf5_hl PROPERTY INTERFACE_LINK_LIBRARIES HDF5::HL)
endif()
if(TARGET HDF5::CXX AND NOT TARGET hdf5::hdf5_cpp)
    add_library(hdf5::hdf5_cpp INTERFACE IMPORTED)
    set_property(TARGET hdf5::hdf5_cpp PROPERTY INTERFACE_LINK_LIBRARIES HDF5::CXX)
endif()
if(TARGET HDF5::HL_CXX AND NOT TARGET hdf5::hdf5_hl_cpp)
    add_library(hdf5::hdf5_hl_cpp INTERFACE IMPORTED)
    set_property(TARGET hdf5::hdf5_hl_cpp PROPERTY INTERFACE_LINK_LIBRARIES HDF5::HL_CXX)
endif()
if(TARGET HDF5::HL AND TARGET HDF5::CXX AND NOT TARGET hdf5::hdf5_hl_cpp)
    add_library(hdf5::hdf5_hl_cpp INTERFACE IMPORTED)
    set_property(TARGET hdf5::hdf5_hl_cpp PROPERTY INTERFACE_LINK_LIBRARIES HDF5::HL_CXX)
endif()
